swagger: '2.0'
info:
  version: v1
  title: Shopping API
basePath: /api/v1

paths:
  '/healthcheck':
    get:
      summary: API healthcheck
      operationId: healthcheck
      x-swagger-router-controller: shopping.controller
      produces:
      - application/json
      responses:
        '200':
          description: successful operation

  '/shopping_lists':
    get:
      summary: Get all shopping lists
      operationId: get_shopping_lists
      x-swagger-router-controller: shopping.controller
      produces:
      - application/json
      responses:
        '200':
          description: successful operation

    post:
      summary: Add Shopping List
      description: Add new shopping list
      operationId: add_shopping_list
      x-swagger-router-controller: shopping.controller
      produces:
        - application/json
      parameters:
        - name: new_shopping_list
          in: body
          required: true
          schema:
            $ref: '#/definitions/new_shopping_list'
      responses:
        '200':
          description: successful operation

  '/shopping_lists/{owner}':
    get:
      summary: Get Shopping List
      description: Get specified shopping list
      operationId: get_shopping_list
      x-swagger-router-controller: shopping.controller
      produces:
        - application/json
      parameters:
        - name: owner
          in: path
          description: Shopping list Owner
          required: true
          type: string
      responses:
        '200':
          description: successful operation

    patch:
      summary: Update Shopping List
      description: Update selected shopping list
      operationId: update_shopping_list
      x-swagger-router-controller: shopping.controller
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: owner
          in: path
          description: Shopping list Owner
          required: true
          type: string
        - name: update_shopping_list_information
          in: body
          description: Update Shopping List information
          required: true
          schema:
            $ref: '#/definitions/update_shopping_list_information'
      responses:
        '202':
          description: Successful operation
    delete:
      summary: Delete Shopping List
      description: Delete given shopping list.
      operationId: delete_shopping_list
      x-swagger-router-controller: shopping.controller
      parameters:
        - name: owner
          in: path
          description: Shopping list Owner
          required: true
          type: string
      responses:
        '200':
          description: Successful operation

  '/products':
    get:
      summary: Get all Products
      description: Get all Products.
      operationId: get_products
      x-swagger-router-controller: shopping.controller
      produces:
        - application/json
      responses:
        '200':
          description: successful operation

    post:
      summary: Add new Product
      operationId: add_product
      x-swagger-router-controller: shopping.controller
      produces:
        - application/json
      parameters:
        - name: new_product
          in: body
          required: true
          schema:
            $ref: '#/definitions/new_product'
      responses:
        '200':
          description: successful operation


  '/products/{name}':
    get:
      summary: Get Product
      description: Get specified Product
      operationId: get_product
      x-swagger-router-controller: shopping.controller
      produces:
        - application/json
      parameters:
        - name: name
          in: path
          description: Product Name
          required: true
          type: string
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/product'

    patch:
      summary: Update Product
      description: Update selected Product
      operationId: update_product
      x-swagger-router-controller: shopping.controller
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: name
          in: path
          description: Product Name
          required: true
          type: string
        - name: update_product_information
          in: body
          description: Product update information
          required: true
          schema:
            $ref: '#/definitions/update_product_information'
      responses:
        '202':
          description: Successful operation

    delete:
      summary: Delete Product
      description: Delete Selected Product.
      operationId: delete_product
      x-swagger-router-controller: shopping.controller
      parameters:
        - name: name
          in: path
          description: Product Name
          required: true
          type: string
      responses:
        '200':
          description: Successful operation

definitions:
  shopping_list:
    type: object
    properties:
      owner:
        description: Name of the owner
        type: string

  new_shopping_list:
    type: object
    required:
      - owner
    properties:
      owner:
        description: New shopping list owner name
        type: string

  update_shopping_list_information:
    type: object
    required:
      - owner
    properties:
      owner:
        description: Set shopping list owner name
        type: string

  product:
    type: object
    properties:
      name:
        description: Product Name
        type: string
      descr:
        description: Product description
        type: string
      owner:
        description: Product owner name, FK to ShoppingList
        type: string
      is_purchased:
        description: Has product been purchased
        type: boolean

  new_product:
    type: object
    properties:
      name:
        description: Product Name
        type: string
      descr:
        description: Product description
        type: string
      shopping_list_id:
        description: Assign Product to given shopping_list.owner Name, FK to ShoppingList
        type: string
      is_purchased:
        description: Has product been purchased
        type: boolean

  update_product_information:
    type: object
    properties:
      name:
        description: Product Name
        type: string
      descr:
        description: Product description
        type: string
      shopping_list_id:
        description: Assign Product to ShoppingList id, FK to ShoppingList
        type: string
      is_purchased:
        description: Has product been purchased
        type: boolean